# Generated by Django 5.0.1 on 2024-02-13 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partrequest',
            old_name='part',
            new_name='parts',
        ),
    ]
