# Generated by Django 5.0.1 on 2024-02-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_rename_part_partrequest_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecheck',
            name='additional',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='vehiclecheck',
            name='headlights',
            field=models.CharField(choices=[('Good', 'Good'), ('Need Replaced', 'Need Replaced')], default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiclecheck',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiclecheck',
            name='oil',
            field=models.CharField(choices=[('Good', 'Good'), ('Low', 'Low')], default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiclecheck',
            name='oil_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclecheck',
            name='taillights',
            field=models.CharField(choices=[('Good', 'Good'), ('Need Replaced', 'Need Replaced')], default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiclecheck',
            name='tires',
            field=models.CharField(choices=[('Good', 'Good'), ('Leaking', 'Leaking'), ('Worn', 'Worn')], default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiclecheck',
            name='vehicle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclecheck',
            name='windshield',
            field=models.CharField(choices=[('Good', 'Good'), ('Cracked', 'Cracked'), ('Chipped', 'Chipped')], default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='vehiclecheck',
            name='wipers',
            field=models.CharField(choices=[('Good', 'Good'), ('Worn', 'Worn')], default='Good', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiclecheck',
            name='miles',
            field=models.IntegerField(default=0),
        ),
    ]
