# Generated by Django 5.0.1 on 2024-02-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0003_vehiclecheck_additional_vehiclecheck_headlights_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclecheck',
            old_name='taillights',
            new_name='tail_lights',
        ),
    ]
