# Generated by Django 5.0.1 on 2024-02-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0005_fuelpurchase_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelpurchase',
            name='image',
            field=models.ImageField(blank=True, default='None', upload_to='djangouploads/files/receipts'),
        ),
    ]
