# Generated by Django 5.0.1 on 2024-02-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0007_test_ans_test_op1_test_op2_test_op3_test_op4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
